export const authCopy = {
  en: {
    home: "Home", workspace: "Workspace", language: "Language", signin: "Photographer sign-in",
    detail: "Sign in with your Google account to enter your private photography workspace.",
    google: "Continue with Google", unavailable: "Sign-in is temporarily unavailable. Please try again later.",
    failed: "Sign-in could not be completed. Please try again.",
    identityOnly: "Signing in does not give this app access to your Drive files.",
    signout: "Sign out", welcome: "Your workspace", account: "Signed in as",
    preparing: "Album creation will become available after Drive folder access is validated.",
    sessionUnavailable: "We couldn’t load your workspace. Please try again.", retry: "Try again",
    driveHeading: "Google Drive", driveDetail: "Connect Drive only when you are ready to choose source photos. The app requests file-specific access, not your entire Drive.",
    connectDrive: "Connect Google Drive", reconnectDrive: "Reconnect Drive", disconnectDrive: "Disconnect",
    connectedAs: "Connected as", connected: "Connected", reauthRequired: "Reconnect required", disconnected: "Disconnected",
    driveUnavailable: "Drive connection status is temporarily unavailable.",
    driveConnectedNotice: "Google Drive was connected securely.",
    driveDisconnectedNotice: "The local Drive connection and stored credential were removed.",
    driveFailedNotice: "The Drive connection could not be changed. Please try again.",
    driveRevocationWarning: "The local credential was removed, but Google revocation could not be confirmed. Review connected apps in your Google Account.",
    scopePilot: "Folder selection is not enabled yet. Access to existing folder contents must be validated with a real Drive account before album import is opened.",
  },
  vi: {
    home: "Trang chủ", workspace: "Không gian làm việc", language: "Ngôn ngữ", signin: "Đăng nhập nhiếp ảnh gia",
    detail: "Đăng nhập bằng tài khoản Google để vào không gian làm việc nhiếp ảnh riêng của bạn.",
    google: "Tiếp tục với Google", unavailable: "Đăng nhập tạm thời chưa khả dụng. Vui lòng thử lại sau.",
    failed: "Không thể hoàn tất đăng nhập. Vui lòng thử lại.",
    identityOnly: "Đăng nhập không cấp quyền truy cập các tệp Drive của bạn cho ứng dụng.",
    signout: "Đăng xuất", welcome: "Không gian làm việc của bạn", account: "Đã đăng nhập với",
    preparing: "Tính năng tạo album sẽ khả dụng sau khi quyền truy cập thư mục Drive được xác minh.",
    sessionUnavailable: "Không thể tải không gian làm việc. Vui lòng thử lại.", retry: "Thử lại",
    driveHeading: "Google Drive", driveDetail: "Chỉ kết nối Drive khi bạn sẵn sàng chọn ảnh nguồn. Ứng dụng yêu cầu quyền theo từng tệp, không phải toàn bộ Drive.",
    connectDrive: "Kết nối Google Drive", reconnectDrive: "Kết nối lại Drive", disconnectDrive: "Ngắt kết nối",
    connectedAs: "Đã kết nối với", connected: "Đã kết nối", reauthRequired: "Cần kết nối lại", disconnected: "Đã ngắt kết nối",
    driveUnavailable: "Tạm thời không thể tải trạng thái kết nối Drive.",
    driveConnectedNotice: "Google Drive đã được kết nối an toàn.",
    driveDisconnectedNotice: "Kết nối Drive cục bộ và thông tin xác thực đã lưu đã được xóa.",
    driveFailedNotice: "Không thể thay đổi kết nối Drive. Vui lòng thử lại.",
    driveRevocationWarning: "Thông tin xác thực cục bộ đã được xóa nhưng chưa thể xác nhận thu hồi phía Google. Hãy kiểm tra các ứng dụng đã kết nối trong Tài khoản Google.",
    scopePilot: "Chức năng chọn thư mục chưa được bật. Quyền truy cập nội dung thư mục hiện có phải được xác minh bằng tài khoản Drive thật trước khi mở tính năng nhập album.",
  },
} as const;
