import { randomBytes } from "node:crypto";

export const webSecurityHeaders = [
  { key: "X-Content-Type-Options", value: "nosniff" },
  { key: "X-Frame-Options", value: "DENY" },
  // Native form navigation across the web/API ports must retain a non-null Origin.
  // Send only the origin (never gallery paths/query strings), and suppress downgrades.
  { key: "Referrer-Policy", value: "strict-origin" },
  { key: "Cross-Origin-Opener-Policy", value: "same-origin" },
  { key: "Cross-Origin-Resource-Policy", value: "same-site" },
  { key: "Permissions-Policy", value: "camera=(), microphone=(), geolocation=(), payment=(), usb=()" },
] as const;

interface BrowserSecurityEnvironment {
  readonly NODE_ENV?: string;
  readonly PUBLIC_WEB_BASE_URL?: string;
  readonly PUBLIC_API_BASE_URL?: string;
}

function origin(value: string): URL | null {
  try {
    const url = new URL(value);
    return ["http:", "https:"].includes(url.protocol) && url.username === "" && url.password === "" &&
      url.pathname === "/" && url.search === "" && url.hash === "" ? url : null;
  } catch { return null; }
}

/** Configured public origins only: never trust Host, forwarded headers or internal API_BASE_URL. */
export function browserSecurityOrigins(environment: BrowserSecurityEnvironment) {
  // Never include loopback development destinations in a hosted production
  // policy merely because public deployment configuration was omitted.
  if (environment.NODE_ENV === "production" &&
    (environment.PUBLIC_WEB_BASE_URL === undefined || environment.PUBLIC_API_BASE_URL === undefined)) return null;
  const web = origin(environment.PUBLIC_WEB_BASE_URL ?? "http://127.0.0.1:3000");
  const api = origin(environment.PUBLIC_API_BASE_URL ?? "http://127.0.0.1:4000");
  if (web === null || api === null || web.hostname !== api.hostname || web.protocol !== api.protocol ||
    (web.protocol === "http:" && !["127.0.0.1", "localhost", "[::1]"].includes(web.hostname))) return null;
  return { web, api };
}

export function createBrowserCsp(nonce: string, environment: BrowserSecurityEnvironment): string {
  // Reject accidental policy injection even though the only production caller
  // supplies cryptographically generated bytes, never a request header.
  if (!/^[A-Za-z0-9+/]{43}=$/.test(nonce) || Buffer.from(nonce, "base64").toString("base64") !== nonce) {
    throw new Error("A valid request nonce is required.");
  }
  const origins = browserSecurityOrigins(environment);
  const development = environment.NODE_ENV === "development";
  const api = origins === null ? "" : ` ${origins.api.origin}`;
  const websocket = development && origins !== null
    ? ` ${origins.web.origin.replace(/^http/, "ws")}` : "";
  return [
    "default-src 'none'",
    `script-src 'self' 'nonce-${nonce}' 'strict-dynamic'${development ? " 'unsafe-eval'" : ""}`,
    "script-src-attr 'none'",
    // Development injects HMR style elements. Production style elements need a
    // nonce; only style attributes remain allowed for bounded photo aspect ratios.
    `style-src 'self' ${development ? "'unsafe-inline'" : `'nonce-${nonce}'`}`,
    "style-src-attr 'unsafe-inline'",
    `img-src 'self'${api}`,
    "font-src 'self'",
    `connect-src 'self'${websocket}`,
    "object-src 'none'",
    "base-uri 'none'",
    // Native POSTs go to the API. Chromium also checks OAuth redirect targets.
    `form-action 'self'${api}${origins === null ? "" : " https://accounts.google.com"}`,
    "frame-src 'none'",
    "frame-ancestors 'none'",
    "worker-src 'none'",
    ...(origins?.web.protocol === "https:" ? ["upgrade-insecure-requests"] : []),
  ].join("; ");
}

export function createRequestCsp(environment: BrowserSecurityEnvironment) {
  const nonce = randomBytes(32).toString("base64");
  return { nonce, csp: createBrowserCsp(nonce, environment) };
}
