export const workspaceCopy = {
  en: {
    albums: "Your albums", empty: "No albums yet. Album import is waiting for Drive folder-access validation.",
    unavailable: "Albums could not be loaded. Please try again.", notFound: "This album was not found.",
    stale: "This page has changed or expired. Return to the first page to see the latest selection.",
    first: "First page", next: "Next page", review: "Review selection", back: "Back to workspace",
    photos: "photos", selected: "selected", created: "Created", updated: "Updated",
    DRAFT: "Draft", PUBLISHED: "Published", ARCHIVED: "Archived", SUBMITTED: "Submitted", LOCKED: "Locked",
    selection: "Client selection", noSelection: "No photographs selected yet.", removed: "No longer in the source folder",
    noComment: "No comment", previewUnavailable: "Preview unavailable", export: "Download filenames (.txt)", lock: "Lock submitted selection",
    reopen: "Reopen for client edits", reopenHelp: "Reopening lets the client edit again and disables export until they resubmit.",
    archive: "Archive album", archiveHelp: "The public gallery will close. Selection history is retained; Drive originals are not deleted.",
    confirmArchive: "I confirm that this public gallery should be archived.", confirmReopen: "I confirm that the client may edit this selection again.",
    changed: "The album was updated.", failed: "The change could not be completed. Refresh and try again.",
    submitted: "Submitted", locked: "Locked", openGallery: "Open client gallery", copy: "Copy gallery link", copied: "Link copied",
    copyFailed: "Copy failed. Select the link below to copy it manually.", protected: "Password protected",
  },
  vi: {
    albums: "Album của bạn", empty: "Chưa có album. Tính năng nhập album đang chờ xác minh quyền truy cập thư mục Drive.",
    unavailable: "Không thể tải album. Vui lòng thử lại.", notFound: "Không tìm thấy album này.",
    stale: "Trang này đã thay đổi hoặc hết hạn. Về trang đầu để xem lựa chọn mới nhất.",
    first: "Trang đầu", next: "Trang tiếp", review: "Xem lựa chọn", back: "Về không gian làm việc",
    photos: "ảnh", selected: "đã chọn", created: "Ngày tạo", updated: "Cập nhật",
    DRAFT: "Bản nháp", PUBLISHED: "Đã xuất bản", ARCHIVED: "Đã lưu trữ", SUBMITTED: "Đã gửi", LOCKED: "Đã khóa",
    selection: "Lựa chọn của khách hàng", noSelection: "Chưa có ảnh nào được chọn.", removed: "Không còn trong thư mục nguồn",
    noComment: "Không có ghi chú", previewUnavailable: "Chưa có bản xem trước", export: "Tải tên tệp (.txt)", lock: "Khóa lựa chọn đã gửi",
    reopen: "Mở lại để khách hàng chỉnh sửa", reopenHelp: "Mở lại cho phép khách hàng chỉnh sửa và tắt xuất tên tệp cho đến khi họ gửi lại.",
    archive: "Lưu trữ album", archiveHelp: "Thư viện công khai sẽ đóng. Lịch sử lựa chọn được giữ lại; ảnh gốc trên Drive không bị xóa.",
    confirmArchive: "Tôi xác nhận lưu trữ thư viện công khai này.", confirmReopen: "Tôi xác nhận cho phép khách hàng chỉnh sửa lại lựa chọn này.",
    changed: "Album đã được cập nhật.", failed: "Không thể hoàn tất thay đổi. Hãy tải lại trang và thử lại.",
    submitted: "Ngày gửi", locked: "Ngày khóa", openGallery: "Mở thư viện khách hàng", copy: "Sao chép liên kết", copied: "Đã sao chép",
    copyFailed: "Không thể sao chép. Hãy chọn liên kết bên dưới để sao chép thủ công.", protected: "Có mật khẩu",
  },
} as const;
